### ISSUE TITLE
R2 produces extra curly brackets in a certain situation

### ISSUE THREAD

**Issue by idosius** [ded/R2#20] opened 2013-01-29 16:30 UTC
The following code:

``` css
.flex-caption { zoom: 1;}
.flex-caption {}
.flex-direction-nav li a {
color: black;
}
```

Produces the following result via R2 (notice the double curly brackets in the beginning):

``` css
.flex-caption{zoom:1;}}.flex-direction-nav li a{color:black;}
```

**Comment by ded** [comment] 2013-01-30 02:06
ugh! i know why this is happening... i'll see if i can patch this....

**Comment by BYK** [comment] 2013-12-04 11:23
This is a duplicate of #22. I'm closing this one since #22 has a better explanation and summary line.

**Closed as completed by BYK** 2013-12-04 11:23 UTC
